[target.'cfg(target_os= "none")']
runner = "bootimage runner"

[build]
target = "x86_64-sd_kernel.json"

[unstable]
json-target-spec = true
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]
panic-abort-tests = true